# Generated by Django 3.2 on 2021-05-02 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام شما')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('desceiption', models.TextField(verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
